name: Freemail package test
on:
  pull_request:
    branches: [main]
    paths:
      - src/**
      - test/**
      - package.json
      - renovate.json
      - tsconfig.json
      - data/**
      - yarn.lock
      - .github/workflows/pr.yml
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and test
        run: |
          yarn install
          yarn test